name: ShoolManagementSystem
description: Navigation and routing sample app
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  adaptive_navigation: ^0.0.3
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_appauth: ^4.2.0
  http: ^0.13.5
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  mask_text_input_formatter: ^2.4.0
  openid_client: ^0.4.6
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  url_launcher: ^6.1.1
  url_strategy: ^0.2.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test: ^1.16.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/dev.json
    - assets/images/
