export 'data/author.dart';
export 'data/book.dart';
export 'data/employee.dart';
export 'data/campus_config_system.dart';
export 'data/address_type.dart';
export 'data/person.dart';
export 'data/vacancy.dart';
export 'data/application.dart';
export 'data/avinya_type.dart';
